config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/badgr-server:
      branch: develop
      repo: https://github.com/PalomoIFCA/badgr-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/badgr-server git:
        commands:
        - /usr/bin/env sh .sqa/script.turquoise_open_rhinoceros.sh
        container: qc.acc_orchid_ardent_tortoise
  QC.Doc:
    repos:
      github.com/PalomoIFCA/badgr-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.strawberry_zany_eel.sh
        container: qc.doc_turmeric_romantic_cassowary
      github.com/PalomoIFCA/badgr-server git:
        commands:
        - /usr/bin/env sh .sqa/script.blush_creative_giraffe.sh
        container: qc.doc_horizon_mysterious_kraken
      github.com/PalomoIFCA/badgr-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.copper_shy_phoenix.sh
        container: qc.doc_wine_brave_capybara
  QC.Lic:
    repos:
      github.com/PalomoIFCA/badgr-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.coral_passionate_cheetah.sh
        container: qc.lic_indigo_independent_finch
  QC.Sec:
    repos:
      github.com/PalomoIFCA/badgr-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.coffee_optimistic_rabbit.sh
        container: qc.sec_glacier_helpful_meerkat
  QC.Sty:
    repos:
      github.com/PalomoIFCA/badgr-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ice_thankful_snail.sh
        container: qc.sty_blush_cranky_quokka
      github.com/PalomoIFCA/badgr-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clove_easygoing_rhinoceros.sh
        container: qc.sty_echelon_nervous_starfish
      github.com/PalomoIFCA/badgr-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.horizon_cheerful_goat.sh
        container: qc.sty_marigold_calm_chinchilla
  QC.Uni:
    repos:
      github.com/PalomoIFCA/badgr-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_brave_pangolin.sh
        container: qc.uni_polar_rustic_toucan
  QC.Ver:
    repos:
      github.com/PalomoIFCA/badgr-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.burgundy_positive_caiman.sh
        container: qc.ver_zinnia_amiable_whale
timeout: 5400
