config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/badgr-server:
      branch: develop
      repo: https://github.com/PalomoIFCA/badgr-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/badgr-server git:
        commands:
        - /usr/bin/env sh .sqa/script.copper_bubbly_walrus.sh
        container: qc.acc_clementine_authentic_gull
  QC.Doc:
    repos:
      github.com/PalomoIFCA/badgr-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.rust_calm_crocodile.sh
        container: qc.doc_plum_melancholy_mink
      github.com/PalomoIFCA/badgr-server git:
        commands:
        - /usr/bin/env sh .sqa/script.bronze_proud_spren.sh
        container: qc.doc_puce_grumpy_macaw
      github.com/PalomoIFCA/badgr-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thistle_adventurous_pelican.sh
        container: qc.doc_flamingo_decisive_snail
  QC.Lic:
    repos:
      github.com/PalomoIFCA/badgr-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_apprehensive_axolotl.sh
        container: qc.lic_glacier_bubbly_porcupine
  QC.Sec:
    repos:
      github.com/PalomoIFCA/badgr-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.red_goofy_dugong.sh
        container: qc.sec_watermelon_savvy_crow
  QC.Sty:
    repos:
      github.com/PalomoIFCA/badgr-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.claret_gracious_goose.sh
        container: qc.sty_brown_feisty_alligator
      github.com/PalomoIFCA/badgr-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.vermilion_reserved_dolphin.sh
        container: qc.sty_ochre_affectionate_tortoise
      github.com/PalomoIFCA/badgr-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.rust_clever_cobra.sh
        container: qc.sty_scarlet_articulate_jackal
  QC.Uni:
    repos:
      github.com/PalomoIFCA/badgr-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.mulberry_grateful_hedgehog.sh
        container: qc.uni_cobalt_humble_sphinx
  QC.Ver:
    repos:
      github.com/PalomoIFCA/badgr-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chili_intuitive_gecko.sh
        container: qc.ver_tan_impulsive_clownfish
timeout: 5400
